name: CICD
on: 
  push:
    branches:
      - main 
jobs:
    AnalisisSAST:
      runs-on: ubuntu-latest
      steps:
      - name: Clone PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'DevSecOps-Ciclo-7'
          repository: 'final-lab'
